### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined 

### ISSUE THREAD

**Issue by manasa-se** [stationkeeping/bootstrap-slider-rails#5]
Installed the gem and added the require files to both application.js and css. I am getting several  Uncaught TypeError: Cannot read property 'style' of undefined on the js file eg (line 85,   this.tooltip.addClass('top')[0].style.top = -this.tooltip.outerHeight() - 14 + 'px';) etc. 

I am following example 1: My view just shows me a blank input due to the error.

```
   HTML 
```

<   input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="0" data-slider-max="20" data-slider-step="1" data-slider-value="14"/>

```
JavaScript  
```

$('#ex1').slider({
    formater: function(value) {
        return 'Current value: ' + value;
    }
});

```
   CSS  
```
# ex1Slider .slider-selection {

```
background: #BABABA;
```

}

**Comment by ysihaoy** [comment]
How did you solve it eventually?

**Comment by manasa91** [comment]
initialize the slider on document ready

**Comment by bkubic** [comment]
@manasa91 Help me out here, because I'm having the same issue. I tried putting the slider initialization in document ready ($('#price-slider').slider();), but it doesn't seem to change anything and I still get the javascript error.
