### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by manojknit426** [stationkeeping/bootstrap-slider-rails#9]
this.tooltip.addClass('top')[0].style.top = -this.tooltip.outerHeight() - 14 + 'px';
		
error come on 85 line

**Comment by ysihaoy** [comment]
same issue here

**Comment by Undistraction** [comment]
Closing as development of this Gem is now taking place [here](https://github.com/YourCursus/bootstrap-slider-rails).
